// <auto-generated />
using System;
using Hukuk.Takip.Sistemi.Entities.Context;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

namespace Hukuk.Takip.Sistemi.Entities.Migrations
{
    [DbContext(typeof(HukukTakipDbContext))]
    [Migration("20210903073412_IhtarEklendi")]
    partial class IhtarEklendi
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "2.1.14-servicing-32113")
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("Hukuk.Takip.Sistemi.Entities.Models.Ihtar", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<DateTime?>("EklenmeTarihi");

                    b.Property<string>("EkleyenKisi");

                    b.Property<DateTime?>("GuncellenmeTarihi");

                    b.Property<string>("Guncelleyen");

                    b.Property<DateTime>("IhtarTarihi");

                    b.Property<DateTime?>("IhtarTebligTarihi");

                    b.Property<decimal?>("IhtarTutar");

                    b.Property<string>("NoterAd");

                    b.Property<string>("SilenKisi");

                    b.Property<bool>("SilindiMi");

                    b.Property<DateTime?>("SilinmeTarihi");

                    b.Property<string>("TakipHesapNo");

                    b.Property<int?>("YevmiyeNo");

                    b.HasKey("Id");

                    b.ToTable("Ihtarlar");
                });

            modelBuilder.Entity("Hukuk.Takip.Sistemi.Entities.Models.IhtarUrun", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<decimal?>("AnaParaTutar");

                    b.Property<DateTime?>("EklenmeTarihi");

                    b.Property<string>("EkleyenKisi");

                    b.Property<decimal?>("FaizTutar");

                    b.Property<DateTime?>("GuncellenmeTarihi");

                    b.Property<string>("Guncelleyen");

                    b.Property<decimal?>("IhtarTutar");

                    b.Property<decimal?>("KomisyonTutar");

                    b.Property<string>("SilenKisi");

                    b.Property<bool>("SilindiMi");

                    b.Property<DateTime?>("SilinmeTarihi");

                    b.Property<decimal?>("ToplamBorc");

                    b.HasKey("Id");

                    b.ToTable("IhtarUrunler");
                });

            modelBuilder.Entity("Hukuk.Takip.Sistemi.Entities.Models.Musteri", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("Ad");

                    b.Property<string>("AnaAdi");

                    b.Property<string>("BabaAdi");

                    b.Property<string>("Cinsiyet");

                    b.Property<DateTime?>("DogumTarihi");

                    b.Property<string>("DogumYeri");

                    b.Property<DateTime?>("EklenmeTarihi");

                    b.Property<string>("EkleyenKisi");

                    b.Property<DateTime?>("GuncellenmeTarihi");

                    b.Property<string>("Guncelleyen");

                    b.Property<bool>("HayattaMi");

                    b.Property<string>("MedeniHali");

                    b.Property<long>("MusteriNo");

                    b.Property<int>("MusteriTipi");

                    b.Property<string>("PasaportNo");

                    b.Property<string>("SilenKisi");

                    b.Property<bool>("SilindiMi");

                    b.Property<DateTime?>("SilinmeTarihi");

                    b.Property<string>("Soyad");

                    b.Property<string>("TCKN");

                    b.Property<string>("TakipSubeAdi");

                    b.Property<int?>("TakipSubeKodu");

                    b.Property<string>("VKN");

                    b.Property<DateTime?>("VefatTarihi");

                    b.HasKey("Id");

                    b.ToTable("Musteriler");
                });

            modelBuilder.Entity("Hukuk.Takip.Sistemi.Entities.Models.MusteriAdres", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("Adres");

                    b.Property<string>("AdresTipi");

                    b.Property<bool>("AnaAdresMi");

                    b.Property<DateTime?>("EklenmeTarihi");

                    b.Property<string>("EkleyenKisi");

                    b.Property<DateTime?>("GuncellenmeTarihi");

                    b.Property<string>("Guncelleyen");

                    b.Property<string>("Ilce");

                    b.Property<string>("Mahalle");

                    b.Property<int>("MusteriId");

                    b.Property<string>("PostaKodu");

                    b.Property<string>("Sehir");

                    b.Property<string>("SilenKisi");

                    b.Property<bool>("SilindiMi");

                    b.Property<DateTime?>("SilinmeTarihi");

                    b.HasKey("Id");

                    b.HasIndex("MusteriId");

                    b.ToTable("MusteriAdresler");
                });

            modelBuilder.Entity("Hukuk.Takip.Sistemi.Entities.Models.MusteriTelefon", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<DateTime?>("EklenmeTarihi");

                    b.Property<string>("EkleyenKisi");

                    b.Property<DateTime?>("GuncellenmeTarihi");

                    b.Property<string>("Guncelleyen");

                    b.Property<int>("MusteriId");

                    b.Property<string>("SilenKisi");

                    b.Property<bool>("SilindiMi");

                    b.Property<DateTime?>("SilinmeTarihi");

                    b.Property<string>("TelefonNo");

                    b.Property<string>("TelefonTİpi");

                    b.HasKey("Id");

                    b.HasIndex("MusteriId");

                    b.ToTable("MusteriTelefonlar");
                });

            modelBuilder.Entity("Hukuk.Takip.Sistemi.Entities.Models.MusteriUrun", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<DateTime?>("EklenmeTarihi");

                    b.Property<string>("EkleyenKisi");

                    b.Property<bool>("ErtelemeVarMi");

                    b.Property<string>("FaizHesap");

                    b.Property<string>("FaizSubeAd");

                    b.Property<int>("FaizSubeKod");

                    b.Property<decimal>("FaizTutar");

                    b.Property<DateTime?>("GuncellenmeTarihi");

                    b.Property<string>("Guncelleyen");

                    b.Property<string>("MasrafHesap");

                    b.Property<string>("MasrafSubeAd");

                    b.Property<int>("MasrafSubeKodu");

                    b.Property<decimal>("MasrafTutar");

                    b.Property<string>("OnErteleme");

                    b.Property<string>("ParaBirimi");

                    b.Property<string>("SilenKisi");

                    b.Property<bool>("SilindiMi");

                    b.Property<DateTime?>("SilinmeTarihi");

                    b.Property<string>("TakipHesapNo");

                    b.Property<string>("TakipSubeAd");

                    b.Property<int>("TakipSubeKod");

                    b.Property<DateTime>("TakipTarihi");

                    b.Property<decimal>("TakipTutar");

                    b.Property<decimal?>("ToplamRiskTutar");

                    b.Property<string>("UrunAd");

                    b.Property<string>("UrunDurumu");

                    b.Property<string>("UrunTipKod");

                    b.HasKey("Id");

                    b.ToTable("MusteriUrunler");
                });

            modelBuilder.Entity("Hukuk.Takip.Sistemi.Entities.Models.MusteriAdres", b =>
                {
                    b.HasOne("Hukuk.Takip.Sistemi.Entities.Models.Musteri", "Musteri")
                        .WithMany("MusteriAdresler")
                        .HasForeignKey("MusteriId")
                        .OnDelete(DeleteBehavior.Cascade);
                });

            modelBuilder.Entity("Hukuk.Takip.Sistemi.Entities.Models.MusteriTelefon", b =>
                {
                    b.HasOne("Hukuk.Takip.Sistemi.Entities.Models.Musteri", "Musteri")
                        .WithMany("MusteriTelefonlar")
                        .HasForeignKey("MusteriId")
                        .OnDelete(DeleteBehavior.Cascade);
                });
#pragma warning restore 612, 618
        }
    }
}
