// <auto-generated />
using System;
using Hukuk.Takip.Sistemi.Entities.Context;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

namespace Hukuk.Takip.Sistemi.Entities.Migrations
{
    [DbContext(typeof(HukukTakipDbContext))]
    [Migration("20210831071918_UpdateMusteriler")]
    partial class UpdateMusteriler
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "2.1.14-servicing-32113")
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("Hukuk.Takip.Sistemi.Entities.Models.Musteri", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("Ad");

                    b.Property<string>("AnaAdi");

                    b.Property<string>("BabaAdi");

                    b.Property<string>("Cinsiyet")
                        .IsRequired()
                        .HasConversion(new ValueConverter<string, string>(v => default(string), v => default(string), new ConverterMappingHints(size: 1)));

                    b.Property<DateTime>("DogumTarihi");

                    b.Property<string>("DogumYeri");

                    b.Property<DateTime>("EklenmeTarihi");

                    b.Property<string>("EkleyenKisi");

                    b.Property<DateTime>("GuncellenmeTarihi");

                    b.Property<string>("Guncelleyen");

                    b.Property<string>("HayattaMi")
                        .IsRequired()
                        .HasConversion(new ValueConverter<string, string>(v => default(string), v => default(string), new ConverterMappingHints(size: 1)));

                    b.Property<string>("MedeniHali")
                        .IsRequired()
                        .HasConversion(new ValueConverter<string, string>(v => default(string), v => default(string), new ConverterMappingHints(size: 1)));

                    b.Property<long>("MusteriNo");

                    b.Property<int>("MusteriTipi");

                    b.Property<string>("PasaportNo");

                    b.Property<string>("SilenKisi");

                    b.Property<string>("SilindiMi")
                        .IsRequired()
                        .HasConversion(new ValueConverter<string, string>(v => default(string), v => default(string), new ConverterMappingHints(size: 1)));

                    b.Property<DateTime>("SilinmeTarihi");

                    b.Property<string>("Soyad");

                    b.Property<string>("TCKN");

                    b.Property<string>("TakipSubeAdi");

                    b.Property<int>("TakipSubeKodu");

                    b.Property<string>("VKN");

                    b.Property<DateTime>("VefatTarihi");

                    b.HasKey("Id");

                    b.ToTable("Musteriler");
                });

            modelBuilder.Entity("Hukuk.Takip.Sistemi.Entities.Models.MusteriAdres", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("Adres");

                    b.Property<string>("AdresTipi");

                    b.Property<string>("AnaAdresMi")
                        .IsRequired()
                        .HasConversion(new ValueConverter<string, string>(v => default(string), v => default(string), new ConverterMappingHints(size: 1)));

                    b.Property<DateTime>("EklenmeTarihi");

                    b.Property<string>("EkleyenKisi");

                    b.Property<DateTime>("GuncellenmeTarihi");

                    b.Property<string>("Guncelleyen");

                    b.Property<string>("Ilce");

                    b.Property<string>("Mahalle");

                    b.Property<int>("MusteriId");

                    b.Property<string>("PostaKodu");

                    b.Property<string>("Sehir");

                    b.Property<string>("SilenKisi");

                    b.Property<string>("SilindiMi")
                        .IsRequired()
                        .HasConversion(new ValueConverter<string, string>(v => default(string), v => default(string), new ConverterMappingHints(size: 1)));

                    b.Property<DateTime>("SilinmeTarihi");

                    b.HasKey("Id");

                    b.HasIndex("MusteriId");

                    b.ToTable("MusteriAdresler");
                });

            modelBuilder.Entity("Hukuk.Takip.Sistemi.Entities.Models.MusteriTelefon", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<DateTime>("EklenmeTarihi");

                    b.Property<string>("EkleyenKisi");

                    b.Property<DateTime>("GuncellenmeTarihi");

                    b.Property<string>("Guncelleyen");

                    b.Property<int>("MusteriId");

                    b.Property<string>("SilenKisi");

                    b.Property<string>("SilindiMi")
                        .IsRequired()
                        .HasConversion(new ValueConverter<string, string>(v => default(string), v => default(string), new ConverterMappingHints(size: 1)));

                    b.Property<DateTime>("SilinmeTarihi");

                    b.Property<string>("TelefonNo");

                    b.Property<string>("TelefonTİpi");

                    b.HasKey("Id");

                    b.HasIndex("MusteriId");

                    b.ToTable("MusteriTelefonlar");
                });

            modelBuilder.Entity("Hukuk.Takip.Sistemi.Entities.Models.MusteriAdres", b =>
                {
                    b.HasOne("Hukuk.Takip.Sistemi.Entities.Models.Musteri", "Musteri")
                        .WithMany("MusteriAdresler")
                        .HasForeignKey("MusteriId")
                        .OnDelete(DeleteBehavior.Cascade);
                });

            modelBuilder.Entity("Hukuk.Takip.Sistemi.Entities.Models.MusteriTelefon", b =>
                {
                    b.HasOne("Hukuk.Takip.Sistemi.Entities.Models.Musteri", "Musteri")
                        .WithMany("MusteriTelefonlar")
                        .HasForeignKey("MusteriId")
                        .OnDelete(DeleteBehavior.Cascade);
                });
#pragma warning restore 612, 618
        }
    }
}
