// <auto-generated />
using System;
using Hukuk.Takip.Sistemi.Entities.Context;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

namespace Hukuk.Takip.Sistemi.Entities.Migrations
{
    [DbContext(typeof(HukukTakipDbContext))]
    [Migration("20211027202516_VeriTabaniOlusturma")]
    partial class VeriTabaniOlusturma
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "2.1.14-servicing-32113")
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("Hukuk.Takip.Sistemi.Entities.Models.Avukat", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnName("Id")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("Ad")
                        .IsRequired()
                        .HasColumnName("Ad")
                        .HasColumnType("varchar(50)");

                    b.Property<bool>("AktifMi")
                        .HasColumnName("AktifMi");

                    b.Property<bool>("DosyaYetkisi")
                        .HasColumnName("DosyaYetkisi");

                    b.Property<DateTime?>("EklenmeTarihi")
                        .HasColumnName("EklenmeTarihi");

                    b.Property<string>("EkleyenKisi")
                        .HasColumnName("EkleyenKisi")
                        .HasColumnType("varchar(20)");

                    b.Property<string>("FaxNo")
                        .HasColumnName("FaxNo")
                        .HasColumnType("varchar(50)");

                    b.Property<DateTime?>("GuncellenmeTarihi")
                        .HasColumnName("GuncellenmeTarihi");

                    b.Property<string>("Guncelleyen")
                        .HasColumnName("Guncelleyen")
                        .HasColumnType("varchar(20)");

                    b.Property<bool>("SilindiMi")
                        .HasColumnName("SilindiMi");

                    b.Property<string>("Soyad")
                        .IsRequired()
                        .HasColumnName("Soyad")
                        .HasColumnType("varchar(50)");

                    b.Property<string>("TCKN")
                        .IsRequired()
                        .HasColumnName("TCKN")
                        .HasColumnType("varchar(11)");

                    b.Property<string>("TelNo")
                        .IsRequired()
                        .HasColumnName("TelNo")
                        .HasColumnType("varchar(20)");

                    b.Property<string>("Tip")
                        .HasColumnName("Tip")
                        .HasColumnType("varchar(150)");

                    b.HasKey("Id");

                    b.ToTable("Avukatlar");
                });

            modelBuilder.Entity("Hukuk.Takip.Sistemi.Entities.Models.AvukatAtananUrun", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnName("Id")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<DateTime>("AtamaTarihi")
                        .HasColumnName("AtamaTarihi");

                    b.Property<int>("AvukatId");

                    b.Property<DateTime>("DelegasyonTarihi")
                        .HasColumnName("DelegasyonTarihi");

                    b.Property<string>("Durum")
                        .HasColumnName("Durum")
                        .HasColumnType("varchar(300)");

                    b.Property<DateTime?>("EklenmeTarihi")
                        .HasColumnName("EklenmeTarihi");

                    b.Property<string>("EkleyenKisi")
                        .HasColumnName("EkleyenKisi")
                        .HasColumnType("varchar(20)");

                    b.Property<DateTime?>("GuncellenmeTarihi")
                        .HasColumnName("GuncellenmeTarihi");

                    b.Property<string>("Guncelleyen")
                        .HasColumnName("Guncelleyen")
                        .HasColumnType("varchar(20)");

                    b.Property<DateTime>("KabulTarihi")
                        .HasColumnName("KabulTarihi");

                    b.Property<int>("MusteriId");

                    b.Property<int>("MusteriUrunId");

                    b.Property<bool>("SilindiMi")
                        .HasColumnName("SilindiMi");

                    b.HasKey("Id");

                    b.HasIndex("AvukatId");

                    b.HasIndex("MusteriId");

                    b.HasIndex("MusteriUrunId");

                    b.ToTable("AvukatAtananUrunler");
                });

            modelBuilder.Entity("Hukuk.Takip.Sistemi.Entities.Models.IcraTakip", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnName("Id")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("Aciklama")
                        .HasColumnName("Aciklama")
                        .HasColumnType("varchar(300)");

                    b.Property<int>("AvukatAtananUrunlerId");

                    b.Property<int?>("AvukatId");

                    b.Property<string>("DosyaNo")
                        .IsRequired()
                        .HasColumnName("DosyaNo")
                        .HasColumnType("varchar(150)");

                    b.Property<DateTime?>("EklenmeTarihi")
                        .HasColumnName("EklenmeTarihi");

                    b.Property<string>("EkleyenKisi")
                        .HasColumnName("EkleyenKisi")
                        .HasColumnType("varchar(20)");

                    b.Property<DateTime?>("GuncellenmeTarihi")
                        .HasColumnName("GuncellenmeTarihi");

                    b.Property<string>("Guncelleyen")
                        .HasColumnName("Guncelleyen")
                        .HasColumnType("varchar(20)");

                    b.Property<string>("IcraDairesi")
                        .IsRequired()
                        .HasColumnName("IcraDairesi")
                        .HasColumnType("varchar(100)");

                    b.Property<int?>("MusteriId");

                    b.Property<bool>("SilindiMi")
                        .HasColumnName("SilindiMi");

                    b.Property<DateTime>("TakipTarihi")
                        .HasColumnName("TakipTarihi");

                    b.Property<string>("TakipTipi")
                        .IsRequired()
                        .HasColumnName("TakipTipi")
                        .HasColumnType("varchar(50)");

                    b.HasKey("Id");

                    b.HasIndex("AvukatAtananUrunlerId");

                    b.HasIndex("AvukatId");

                    b.HasIndex("MusteriId");

                    b.ToTable("IcraTakipler");
                });

            modelBuilder.Entity("Hukuk.Takip.Sistemi.Entities.Models.Ihtar", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnName("Id")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<DateTime?>("EklenmeTarihi")
                        .HasColumnName("EklenmeTarihi");

                    b.Property<string>("EkleyenKisi")
                        .HasColumnName("EkleyenKisi")
                        .HasColumnType("varchar(20)");

                    b.Property<DateTime?>("GuncellenmeTarihi")
                        .HasColumnName("GuncellenmeTarihi");

                    b.Property<string>("Guncelleyen")
                        .HasColumnName("Guncelleyen")
                        .HasColumnType("varchar(20)");

                    b.Property<DateTime>("IhtarTarihi")
                        .HasColumnName("IhtarTarihi");

                    b.Property<DateTime?>("IhtarTebligTarihi")
                        .HasColumnName("IhtarTebliğTarihi");

                    b.Property<decimal?>("IhtarTutar")
                        .HasColumnName("IhtarTutar");

                    b.Property<int>("MusteriId");

                    b.Property<string>("NoterAd")
                        .IsRequired()
                        .HasColumnName("NoterAd")
                        .HasColumnType("varchar(100)");

                    b.Property<bool>("SilindiMi")
                        .HasColumnName("SilindiMi");

                    b.Property<string>("TakipHesapNo")
                        .HasColumnName("TakipHesapNo")
                        .HasColumnType("varchar(25)");

                    b.Property<int?>("YevmiyeNo")
                        .HasColumnName("YevmiyeNo");

                    b.HasKey("Id");

                    b.HasIndex("MusteriId");

                    b.ToTable("Ihtarlar");
                });

            modelBuilder.Entity("Hukuk.Takip.Sistemi.Entities.Models.IhtarUrun", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnName("Id")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<decimal?>("AnaParaTutar")
                        .HasColumnName("AnaParaTutar");

                    b.Property<DateTime?>("EklenmeTarihi")
                        .HasColumnName("EklenmeTarihi");

                    b.Property<string>("EkleyenKisi")
                        .HasColumnName("EkleyenKisi")
                        .HasColumnType("varchar(20)");

                    b.Property<decimal?>("FaizTutar")
                        .HasColumnName("FaizTutar");

                    b.Property<DateTime?>("GuncellenmeTarihi")
                        .HasColumnName("GuncellenmeTarihi");

                    b.Property<string>("Guncelleyen")
                        .HasColumnName("Guncelleyen")
                        .HasColumnType("varchar(20)");

                    b.Property<int>("IhtarId");

                    b.Property<decimal?>("IhtarTutar")
                        .HasColumnName("IhtarTutar");

                    b.Property<decimal?>("KomisyonTutar")
                        .HasColumnName("KomisyonTutar");

                    b.Property<int>("MusteriUrunId");

                    b.Property<bool>("SilindiMi")
                        .HasColumnName("SilindiMi");

                    b.Property<decimal?>("ToplamBorc")
                        .HasColumnName("ToplamBorc");

                    b.HasKey("Id");

                    b.HasIndex("IhtarId");

                    b.HasIndex("MusteriUrunId");

                    b.ToTable("IhtarUrunler");
                });

            modelBuilder.Entity("Hukuk.Takip.Sistemi.Entities.Models.Musteri", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnName("Id")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("Ad")
                        .IsRequired()
                        .HasColumnName("Ad")
                        .HasColumnType("varchar(25)");

                    b.Property<string>("AnaAdi")
                        .HasColumnName("AnaAdi")
                        .HasColumnType("varchar(25)");

                    b.Property<string>("BabaAdi")
                        .HasColumnName("BabaAdi")
                        .HasColumnType("varchar(25)");

                    b.Property<string>("Cinsiyet")
                        .HasColumnName("Cinsiyet")
                        .HasColumnType("varchar(10)");

                    b.Property<DateTime?>("DogumTarihi")
                        .HasColumnName("DogumTarihi");

                    b.Property<string>("DogumYeri")
                        .HasColumnName("DogumYeri")
                        .HasColumnType("varchar(25)");

                    b.Property<DateTime?>("EklenmeTarihi")
                        .HasColumnName("EklenmeTarihi");

                    b.Property<string>("EkleyenKisi")
                        .HasColumnName("EkleyenKisi")
                        .HasColumnType("varchar(20)");

                    b.Property<DateTime?>("GuncellenmeTarihi")
                        .HasColumnName("GuncellenmeTarihi");

                    b.Property<string>("Guncelleyen")
                        .HasColumnName("Guncelleyen")
                        .HasColumnType("varchar(20)");

                    b.Property<bool>("HayattaMi")
                        .HasColumnName("HayattaMi");

                    b.Property<string>("MedeniHali")
                        .HasColumnName("MedeniHali")
                        .HasColumnType("varchar(10)");

                    b.Property<long>("MusteriNo")
                        .HasColumnName("MusteriNo");

                    b.Property<int>("MusteriTipi")
                        .HasColumnName("MusteriTipi");

                    b.Property<string>("PasaportNo")
                        .HasColumnName("PasaportNo")
                        .HasColumnType("varchar(10)");

                    b.Property<bool>("SilindiMi")
                        .HasColumnName("SilindiMi");

                    b.Property<string>("Soyad")
                        .IsRequired()
                        .HasColumnName("Soyad")
                        .HasColumnType("varchar(25)");

                    b.Property<string>("TCKN")
                        .HasColumnName("TCKN")
                        .HasColumnType("varchar(11)");

                    b.Property<string>("TakipSubeAdi")
                        .HasColumnName("TakipSubeAdi")
                        .HasColumnType("varchar(100)");

                    b.Property<int?>("TakipSubeKodu")
                        .HasColumnName("TakipSubeKodu");

                    b.Property<string>("VKN")
                        .HasColumnName("VKN")
                        .HasColumnType("varchar(10)");

                    b.Property<DateTime?>("VefatTarihi")
                        .HasColumnName("VefatTarihi");

                    b.HasKey("Id");

                    b.ToTable("Musteriler");
                });

            modelBuilder.Entity("Hukuk.Takip.Sistemi.Entities.Models.MusteriAdres", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnName("Id")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("Adres")
                        .IsRequired()
                        .HasColumnName("Adres")
                        .HasColumnType("varchar(300)");

                    b.Property<string>("AdresTipi")
                        .IsRequired()
                        .HasColumnName("AdresTipi")
                        .HasColumnType("varchar(25)");

                    b.Property<bool>("AnaAdresMi")
                        .HasColumnName("AnaAdresMi");

                    b.Property<DateTime?>("EklenmeTarihi")
                        .HasColumnName("EklenmeTarihi");

                    b.Property<string>("EkleyenKisi")
                        .HasColumnName("EkleyenKisi")
                        .HasColumnType("varchar(20)");

                    b.Property<DateTime?>("GuncellenmeTarihi")
                        .HasColumnName("GuncellenmeTarihi");

                    b.Property<string>("Guncelleyen")
                        .HasColumnName("Guncelleyen")
                        .HasColumnType("varchar(20)");

                    b.Property<string>("Ilce")
                        .IsRequired()
                        .HasColumnName("Ilce")
                        .HasColumnType("varchar(40)");

                    b.Property<string>("Mahalle")
                        .IsRequired()
                        .HasColumnName("Mahalle")
                        .HasColumnType("varchar(50)");

                    b.Property<int>("MusteriId");

                    b.Property<string>("PostaKodu")
                        .IsRequired()
                        .HasColumnName("PostaKodu")
                        .HasColumnType("varchar(5)");

                    b.Property<string>("Sehir")
                        .IsRequired()
                        .HasColumnName("Sehir")
                        .HasColumnType("varchar(30)");

                    b.Property<bool>("SilindiMi")
                        .HasColumnName("SilindiMi");

                    b.HasKey("Id");

                    b.HasIndex("MusteriId");

                    b.ToTable("MusteriAdresler");
                });

            modelBuilder.Entity("Hukuk.Takip.Sistemi.Entities.Models.MusteriTelefon", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnName("Id")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<DateTime?>("EklenmeTarihi")
                        .HasColumnName("EklenmeTarihi");

                    b.Property<string>("EkleyenKisi")
                        .HasColumnName("EkleyenKisi")
                        .HasColumnType("varchar(20)");

                    b.Property<DateTime?>("GuncellenmeTarihi")
                        .HasColumnName("GuncellenmeTarihi");

                    b.Property<string>("Guncelleyen")
                        .HasColumnName("Guncelleyen")
                        .HasColumnType("varchar(20)");

                    b.Property<int>("MusteriId");

                    b.Property<bool>("SilindiMi")
                        .HasColumnName("SilindiMi");

                    b.Property<string>("TelefonNo")
                        .IsRequired()
                        .HasColumnName("TelefonNo")
                        .HasColumnType("varchar(20)");

                    b.Property<string>("TelefonTİpi")
                        .IsRequired()
                        .HasColumnName("TelefonTİpi")
                        .HasColumnType("varchar(20)");

                    b.HasKey("Id");

                    b.HasIndex("MusteriId");

                    b.ToTable("MusteriTelefonlar");
                });

            modelBuilder.Entity("Hukuk.Takip.Sistemi.Entities.Models.MusteriUrun", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnName("Id")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<DateTime?>("EklenmeTarihi")
                        .HasColumnName("EklenmeTarihi");

                    b.Property<string>("EkleyenKisi")
                        .HasColumnName("EkleyenKisi")
                        .HasColumnType("varchar(20)");

                    b.Property<bool>("ErtelemeVarMi")
                        .HasColumnName("ErtelemeVarMi");

                    b.Property<string>("FaizHesap")
                        .IsRequired()
                        .HasColumnName("FaizHesap")
                        .HasColumnType("varchar(8)");

                    b.Property<string>("FaizSubeAd")
                        .IsRequired()
                        .HasColumnName("FaizSubeAd")
                        .HasColumnType("varchar(125)");

                    b.Property<string>("FaizSubeKod")
                        .IsRequired()
                        .HasConversion(new ValueConverter<string, string>(v => default(string), v => default(string), new ConverterMappingHints(size: 64)))
                        .HasColumnName("FaizSubeKod")
                        .HasColumnType("varchar(25)");

                    b.Property<decimal>("FaizTutar")
                        .HasColumnName("FaizTutar");

                    b.Property<DateTime?>("GuncellenmeTarihi")
                        .HasColumnName("GuncellenmeTarihi");

                    b.Property<string>("Guncelleyen")
                        .HasColumnName("Guncelleyen")
                        .HasColumnType("varchar(20)");

                    b.Property<string>("MasrafHesap")
                        .IsRequired()
                        .HasColumnName("MasrafHesap")
                        .HasColumnType("varchar(8)");

                    b.Property<string>("MasrafSubeAd")
                        .IsRequired()
                        .HasColumnName("MasrafSubeAd")
                        .HasColumnType("varchar(140)");

                    b.Property<int>("MasrafSubeKodu")
                        .HasColumnName("MasrafSubeKodu");

                    b.Property<decimal>("MasrafTutar")
                        .HasColumnName("MasrafTutar");

                    b.Property<int?>("MusteriId");

                    b.Property<string>("OnErteleme")
                        .HasColumnName("OnErteleme")
                        .HasColumnType("varchar(20)");

                    b.Property<string>("ParaBirimi")
                        .IsRequired()
                        .HasColumnName("ParaBirimi")
                        .HasColumnType("varchar(20)");

                    b.Property<bool>("SilindiMi")
                        .HasColumnName("SilindiMi");

                    b.Property<string>("TakipHesapNo")
                        .IsRequired()
                        .HasColumnName("TakipHesapNo")
                        .HasColumnType("varchar(8)");

                    b.Property<string>("TakipSubeAd")
                        .IsRequired()
                        .HasColumnName("TakipSubeAd")
                        .HasColumnType("varchar(50)");

                    b.Property<string>("TakipSubeKod")
                        .IsRequired()
                        .HasConversion(new ValueConverter<string, string>(v => default(string), v => default(string), new ConverterMappingHints(size: 64)))
                        .HasColumnName("TakipSubeKod")
                        .HasColumnType("varchar(25)");

                    b.Property<DateTime>("TakipTarihi")
                        .HasColumnName("TakipTarihi");

                    b.Property<string>("TakipTutar")
                        .IsRequired()
                        .HasConversion(new ValueConverter<string, string>(v => default(string), v => default(string), new ConverterMappingHints(size: 64)))
                        .HasColumnName("TakipTutar")
                        .HasColumnType("varchar(40)");

                    b.Property<decimal?>("ToplamRiskTutar")
                        .HasColumnName("ToplamRiskTutar");

                    b.Property<string>("UrunAd")
                        .IsRequired()
                        .HasColumnName("UrunAd")
                        .HasColumnType("varchar(40)");

                    b.Property<string>("UrunDurumu")
                        .HasColumnName("UrunDurumu")
                        .HasColumnType("varchar(140)");

                    b.Property<string>("UrunTipKod")
                        .IsRequired()
                        .HasColumnName("UrunTipKod")
                        .HasColumnType("varchar(40)");

                    b.HasKey("Id");

                    b.HasIndex("MusteriId");

                    b.ToTable("MusteriUrunler");
                });

            modelBuilder.Entity("Hukuk.Takip.Sistemi.Entities.Models.AvukatAtananUrun", b =>
                {
                    b.HasOne("Hukuk.Takip.Sistemi.Entities.Models.Avukat", "Avukat")
                        .WithMany()
                        .HasForeignKey("AvukatId")
                        .OnDelete(DeleteBehavior.Cascade);

                    b.HasOne("Hukuk.Takip.Sistemi.Entities.Models.Musteri", "Musteri")
                        .WithMany()
                        .HasForeignKey("MusteriId")
                        .OnDelete(DeleteBehavior.Cascade);

                    b.HasOne("Hukuk.Takip.Sistemi.Entities.Models.MusteriUrun", "MusteriUrun")
                        .WithMany()
                        .HasForeignKey("MusteriUrunId")
                        .OnDelete(DeleteBehavior.Cascade);
                });

            modelBuilder.Entity("Hukuk.Takip.Sistemi.Entities.Models.IcraTakip", b =>
                {
                    b.HasOne("Hukuk.Takip.Sistemi.Entities.Models.AvukatAtananUrun", "AvukatAtananUrun")
                        .WithMany()
                        .HasForeignKey("AvukatAtananUrunlerId")
                        .OnDelete(DeleteBehavior.Cascade);

                    b.HasOne("Hukuk.Takip.Sistemi.Entities.Models.Avukat", "Avukat")
                        .WithMany()
                        .HasForeignKey("AvukatId");

                    b.HasOne("Hukuk.Takip.Sistemi.Entities.Models.Musteri", "Musteri")
                        .WithMany()
                        .HasForeignKey("MusteriId");
                });

            modelBuilder.Entity("Hukuk.Takip.Sistemi.Entities.Models.Ihtar", b =>
                {
                    b.HasOne("Hukuk.Takip.Sistemi.Entities.Models.Musteri", "Musteri")
                        .WithMany()
                        .HasForeignKey("MusteriId")
                        .OnDelete(DeleteBehavior.Cascade);
                });

            modelBuilder.Entity("Hukuk.Takip.Sistemi.Entities.Models.IhtarUrun", b =>
                {
                    b.HasOne("Hukuk.Takip.Sistemi.Entities.Models.Ihtar", "Ihtar")
                        .WithMany()
                        .HasForeignKey("IhtarId")
                        .OnDelete(DeleteBehavior.Cascade);

                    b.HasOne("Hukuk.Takip.Sistemi.Entities.Models.MusteriUrun", "MusteriUrun")
                        .WithMany()
                        .HasForeignKey("MusteriUrunId")
                        .OnDelete(DeleteBehavior.Cascade);
                });

            modelBuilder.Entity("Hukuk.Takip.Sistemi.Entities.Models.MusteriAdres", b =>
                {
                    b.HasOne("Hukuk.Takip.Sistemi.Entities.Models.Musteri", "Musteri")
                        .WithMany()
                        .HasForeignKey("MusteriId")
                        .OnDelete(DeleteBehavior.Cascade);
                });

            modelBuilder.Entity("Hukuk.Takip.Sistemi.Entities.Models.MusteriTelefon", b =>
                {
                    b.HasOne("Hukuk.Takip.Sistemi.Entities.Models.Musteri", "Musteri")
                        .WithMany()
                        .HasForeignKey("MusteriId")
                        .OnDelete(DeleteBehavior.Cascade);
                });

            modelBuilder.Entity("Hukuk.Takip.Sistemi.Entities.Models.MusteriUrun", b =>
                {
                    b.HasOne("Hukuk.Takip.Sistemi.Entities.Models.Musteri", "Musteri")
                        .WithMany()
                        .HasForeignKey("MusteriId");
                });
#pragma warning restore 612, 618
        }
    }
}
